"use client";

/**
 * BlurredPhoto — the blur-to-reveal photo surface for posts and profiles.
 *
 * FEATURE-FLAGGED OFF — this component renders nothing until
 * NEXT_PUBLIC_FEATURE_PHOTO_BLUR=true (see src/lib/flags.ts). It is not
 * mounted anywhere yet; when photos ship (Phase 4 of the pivot plan) it
 * drops into post cards and profile panels as-is.
 *
 * Contract:
 * - Unrevealed viewers receive ONLY `blurDataUrl` (a ~300-byte placeholder
 *   generated by src/lib/blur.ts). `src` must be null/undefined until the
 *   server has granted this viewer a reveal — never pass the real URL and
 *   rely on CSS to hide it.
 * - `revealed` flips the crossfade once `src` arrives.
 * - `onRequestReveal` wires to the future reveal-grant endpoint; the button
 *   reflects `requestState`.
 */

import { useState } from "react";
import { FEATURES } from "@/lib/flags";

type RequestState = "idle" | "requested";

type Props = {
  /** Tiny base64 placeholder — the only image unrevealed viewers get. */
  blurDataUrl: string;
  /** Full image URL. Only present once the server has granted a reveal. */
  src?: string | null;
  alt: string;
  revealed: boolean;
  /** Camera-only "right now" capture — shows the LIVE badge. */
  isLive?: boolean;
  /** Width / height, reserved before load. Defaults to 1 (square). */
  aspectRatio?: number;
  /** Present when the viewer may ask the poster for a reveal. */
  onRequestReveal?: () => void;
  requestState?: RequestState;
};

export default function BlurredPhoto({
  blurDataUrl,
  src,
  alt,
  revealed,
  isLive = false,
  aspectRatio = 1,
  onRequestReveal,
  requestState = "idle",
}: Props) {
  const [fullLoaded, setFullLoaded] = useState(false);

  // Hard gate: feature is dark until legal review clears photos.
  if (!FEATURES.photoBlur) return null;

  const showFull = revealed && Boolean(src);

  return (
    <div
      className="relative w-full overflow-hidden rounded-xl border border-white/10 bg-[#0f0d18]"
      style={{ aspectRatio }}
    >
      {/* Placeholder layer: upscaled micro-image + heavy blur. Always mounted
          so the reveal crossfades from it instead of popping. */}
      <img
        src={blurDataUrl}
        alt={showFull ? "" : alt}
        aria-hidden={showFull}
        draggable={false}
        className="absolute inset-0 h-full w-full scale-110 object-cover blur-2xl"
      />

      {/* Full-resolution layer — only ever mounted post-reveal. */}
      {showFull && (
        <img
          src={src!}
          alt={alt}
          draggable={false}
          onLoad={() => setFullLoaded(true)}
          className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-500 ${
            fullLoaded ? "opacity-100" : "opacity-0"
          }`}
        />
      )}

      {/* Lock overlay + reveal request, unrevealed state only. */}
      {!showFull && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-black/30 p-3 text-center">
          <svg
            width="22"
            height="22"
            viewBox="0 0 24 24"
            fill="none"
            stroke="#FF8A1E"
            strokeWidth={1.8}
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden
          >
            <rect x="5" y="11" width="14" height="9" rx="2" />
            <path d="M8 11V8a4 4 0 0 1 8 0v3" />
          </svg>
          {onRequestReveal &&
            (requestState === "requested" ? (
              <p className="text-[11px] font-semibold text-white/60">
                Reveal requested
              </p>
            ) : (
              <button
                type="button"
                onClick={onRequestReveal}
                className="rounded-full border border-[#FF8A1E]/40 bg-[#FF8A1E]/15 px-3 py-1.5 text-[11px] font-semibold text-[#FF8A1E] transition hover:bg-[#FF8A1E]/25"
              >
                Ask to reveal
              </button>
            ))}
        </div>
      )}

      {/* LIVE badge — camera-only capture, matches the presence glow. */}
      {isLive && (
        <span
          className="absolute left-2 top-2 flex items-center gap-1 rounded-full bg-black/60 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-[#FF9E2C]"
          style={{ textShadow: "0 0 6px #FF9E2C" }}
        >
          <span
            className="h-1.5 w-1.5 rounded-full bg-[#FF9E2C]"
            style={{ boxShadow: "0 0 6px #FF9E2C" }}
          />
          Live
        </span>
      )}
    </div>
  );
}
